'use strict';function n(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function p(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:n(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}function r(a,b){return Object.prototype.hasOwnProperty.call(a,b)}
var v=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};function ca(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var x=ca(this);
function y(a,b){if(b)a:{var c=x;a=a.split(".");for(var d=0;d<a.length-1;d++){var k=a[d];if(!(k in c))break a;c=c[k]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&v(c,a,{configurable:!0,writable:!0,value:b})}}var da=typeof Object.assign=="function"?Object.assign:function(a,b){if(a==null)throw new TypeError("No nullish arg");a=Object(a);for(var c=1;c<arguments.length;c++){var d=arguments[c];if(d)for(var k in d)r(d,k)&&(a[k]=d[k])}return a};y("Object.assign",function(a){return a||da});
function B(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");}function C(){this.C=!1;this.l=null;this.o=void 0;this.h=1;this.m=this.u=0;this.H=this.j=null}function D(a){if(a.C)throw new TypeError("Generator is already running");a.C=!0}C.prototype.F=function(a){this.o=a};function E(a,b){a.j={L:b,isException:!0};a.h=a.u||a.m}C.prototype.getNextAddressJsc=function(){return this.h};C.prototype.getYieldResultJsc=function(){return this.o};
C.prototype.return=function(a){this.j={return:a};this.h=this.m};C.prototype["return"]=C.prototype.return;C.prototype.O=function(a){this.j={B:a};this.m<a?(this.h=a,this.j=null):this.h=this.m};C.prototype.jumpThroughFinallyBlocks=C.prototype.O;C.prototype.i=function(a,b){this.h=b;return{value:a}};C.prototype.yield=C.prototype.i;C.prototype.R=function(a,b){a=p(a);var c=a.next();B(c);if(c.done)this.o=c.value,this.h=b;else return this.l=a,this.i(c.value,b)};C.prototype.yieldAll=C.prototype.R;
C.prototype.B=function(a){this.h=a};C.prototype.jumpTo=C.prototype.B;C.prototype.I=function(){this.h=0};C.prototype.jumpToEnd=C.prototype.I;C.prototype.A=function(a,b){this.u=a;b!=void 0&&(this.m=b)};C.prototype.setCatchFinallyBlocks=C.prototype.A;C.prototype.P=function(a){this.u=0;this.m=a||0};C.prototype.setFinallyBlock=C.prototype.P;C.prototype.D=function(a,b){this.h=a;this.u=b||0};C.prototype.leaveTryBlock=C.prototype.D;C.prototype.v=function(a){this.u=a||0;a=this.j.L;this.j=null;return a};
C.prototype.enterCatchBlock=C.prototype.v;C.prototype.G=function(a,b,c){c?this.H[c]=this.j:this.H=[this.j];this.u=a||0;this.m=b||0;this.j=null};C.prototype.enterFinallyBlock=C.prototype.G;C.prototype.K=function(a,b){b=this.H.splice(b||0)[0];(b=this.j=this.j||b)?b.isException?this.h=this.u||this.m:b.B!=void 0&&this.m<b.B?(this.h=b.B,this.j=null):this.h=this.m:this.h=a};C.prototype.leaveFinallyBlock=C.prototype.K;C.prototype.N=function(a){return new F(a)};C.prototype.forIn=C.prototype.N;
function F(a){this.j=a;this.h=[];for(var b in a)this.h.push(b);this.h.reverse()}F.prototype.i=function(){for(;this.h.length>0;){var a=this.h.pop();if(a in this.j)return a}return null};F.prototype.getNext=F.prototype.i;function ea(a){this.h=new C;this.i=a}function fa(a,b){D(a.h);var c=a.h.l;if(c)return G(a,"return"in c?c["return"]:function(d){return{value:d,done:!0}},b,a.h.return);a.h.return(b);return H(a)}
function G(a,b,c,d){try{var k=b.call(a.h.l,c);B(k);if(!k.done)return a.h.C=!1,k;var l=k.value}catch(g){return a.h.l=null,E(a.h,g),H(a)}a.h.l=null;d.call(a.h,l);return H(a)}function H(a){for(;a.h.h;)try{var b=a.i(a.h);if(b)return a.h.C=!1,{value:b.value,done:!1}}catch(c){a.h.o=void 0,E(a.h,c)}a.h.C=!1;if(a.h.j){b=a.h.j;a.h.j=null;if(b.isException)throw b.L;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function ha(a){this.next=function(b){D(a.h);a.h.l?b=G(a,a.h.l.next,b,a.h.F):(a.h.F(b),b=H(a));return b};this.throw=function(b){D(a.h);if(a.h.l){var c=a.h.l["throw"];if(c)var d=G(a,c,b,a.h.F);else{b=a.h.l;a.h.l=null;try{b["return"]&&(d=b["return"](),B(d)),E(a.h,new TypeError("The iterator does not provide a 'throw' method."))}catch(k){E(a.h,k)}d=H(a)}}else E(a.h,b),d=H(a);return d};this.return=function(b){return fa(a,b)};this[Symbol.iterator]=function(){return this}}
function ia(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}return new Promise(function(d,k){function l(g){g.done?d(g.value):Promise.resolve(g.value).then(b,c).then(l,k)}l(a.next())})}function I(a){return ia(new ha(new ea(a)))}function ja(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b}
y("Symbol",function(a){function b(l){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(l||"")+"_"+k++,l)}function c(l,g){this.h=l;v(this,"description",{configurable:!0,writable:!0,value:g})}if(a)return a;c.prototype.toString=function(){return this.h};var d="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",k=0;return b});
y("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");v(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return J(n(this))}});return a});function J(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
y("Promise",function(a){function b(g){this.i=0;this.j=void 0;this.h=[];this.u=!1;var e=this.l();try{g(e.resolve,e.reject)}catch(f){e.reject(f)}}function c(){this.h=null}function d(g){return g instanceof b?g:new b(function(e){e(g)})}if(a)return a;c.prototype.i=function(g){if(this.h==null){this.h=[];var e=this;this.j(function(){e.m()})}this.h.push(g)};var k=x.setTimeout;c.prototype.j=function(g){k(g,0)};c.prototype.m=function(){for(;this.h&&this.h.length;){var g=this.h;this.h=[];for(var e=0;e<g.length;++e){var f=
g[e];g[e]=null;try{f()}catch(h){this.l(h)}}}this.h=null};c.prototype.l=function(g){this.j(function(){throw g;})};b.prototype.l=function(){function g(h){return function(m){f||(f=!0,h.call(e,m))}}var e=this,f=!1;return{resolve:g(this.F),reject:g(this.m)}};b.prototype.F=function(g){if(g===this)this.m(new TypeError("A Promise cannot resolve to itself"));else if(g instanceof b)this.H(g);else{a:switch(typeof g){case "object":var e=g!=null;break a;case "function":e=!0;break a;default:e=!1}e?this.D(g):this.o(g)}};
b.prototype.D=function(g){var e=void 0;try{e=g.then}catch(f){this.m(f);return}typeof e=="function"?this.I(e,g):this.o(g)};b.prototype.m=function(g){this.v(2,g)};b.prototype.o=function(g){this.v(1,g)};b.prototype.v=function(g,e){if(this.i!=0)throw Error("Cannot settle("+g+", "+e+"): Promise already settled in state"+this.i);this.i=g;this.j=e;this.i===2&&this.G();this.A()};b.prototype.G=function(){var g=this;k(function(){if(g.C()){var e=x.console;typeof e!=="undefined"&&e.error(g.j)}},1)};b.prototype.C=
function(){if(this.u)return!1;var g=x.CustomEvent,e=x.Event,f=x.dispatchEvent;if(typeof f==="undefined")return!0;typeof g==="function"?g=new g("unhandledrejection",{cancelable:!0}):typeof e==="function"?g=new e("unhandledrejection",{cancelable:!0}):(g=x.document.createEvent("CustomEvent"),g.initCustomEvent("unhandledrejection",!1,!0,g));g.promise=this;g.reason=this.j;return f(g)};b.prototype.A=function(){if(this.h!=null){for(var g=0;g<this.h.length;++g)l.i(this.h[g]);this.h=null}};var l=new c;b.prototype.H=
function(g){var e=this.l();g.J(e.resolve,e.reject)};b.prototype.I=function(g,e){var f=this.l();try{g.call(e,f.resolve,f.reject)}catch(h){f.reject(h)}};b.prototype.then=function(g,e){function f(t,w){return typeof t=="function"?function(z){try{h(t(z))}catch(A){m(A)}}:w}var h,m,q=new b(function(t,w){h=t;m=w});this.J(f(g,h),f(e,m));return q};b.prototype.catch=function(g){return this.then(void 0,g)};b.prototype.J=function(g,e){function f(){switch(h.i){case 1:g(h.j);break;case 2:e(h.j);break;default:throw Error("Unexpected state: "+
h.i);}}var h=this;this.h==null?l.i(f):this.h.push(f);this.u=!0};b.resolve=d;b.reject=function(g){return new b(function(e,f){f(g)})};b.race=function(g){return new b(function(e,f){for(var h=p(g),m=h.next();!m.done;m=h.next())d(m.value).J(e,f)})};b.all=function(g){var e=p(g),f=e.next();return f.done?d([]):new b(function(h,m){function q(z){return function(A){t[z]=A;w--;w==0&&h(t)}}var t=[],w=0;do t.push(void 0),w++,d(f.value).J(q(t.length-1),m),f=e.next();while(!f.done)})};return b});
function K(a,b,c){if(a==null)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""}y("String.prototype.repeat",function(a){return a?a:function(b){var c=K(this,null,"repeat");if(b<0||b>1342177279)throw new RangeError("Invalid count value");b|=0;for(var d="";b;)if(b&1&&(d+=c),b>>>=1)c+=c;return d}});
y("String.prototype.padStart",function(a){return a?a:function(b,c){var d=K(this,null,"padStart");b-=d.length;c=c!==void 0?String(c):" ";return(b>0&&c?c.repeat(Math.ceil(b/c.length)).substring(0,b):"")+d}});y("Object.is",function(a){return a?a:function(b,c){return b===c?b!==0||1/b===1/c:b!==b&&c!==c}});
y("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var k=d.length;c=c||0;for(c<0&&(c=Math.max(c+k,0));c<k;c++){var l=d[c];if(l===b||Object.is(l,b))return!0}return!1}});y("String.prototype.includes",function(a){return a?a:function(b,c){return K(this,b,"includes").indexOf(b,c||0)!==-1}});
y("WeakMap",function(a){function b(f){this.h=(e+=Math.random()+1).toString();if(f){f=p(f);for(var h;!(h=f.next()).done;)h=h.value,this.set(h[0],h[1])}}function c(){}function d(f){var h=typeof f;return h==="object"&&f!==null||h==="function"}function k(f){if(!r(f,g)){var h=new c;v(f,g,{value:h})}}function l(f){var h=Object[f];h&&(Object[f]=function(m){if(m instanceof c)return m;Object.isExtensible(m)&&k(m);return h(m)})}if(function(){if(!a||!Object.seal)return!1;try{var f=Object.seal({}),h=Object.seal({}),
m=new a([[f,2],[h,3]]);if(m.get(f)!=2||m.get(h)!=3)return!1;m.delete(f);m.set(h,4);return!m.has(f)&&m.get(h)==4}catch(q){return!1}}())return a;var g="$jscomp_hidden_"+Math.random();l("freeze");l("preventExtensions");l("seal");var e=0;b.prototype.set=function(f,h){if(!d(f))throw Error("Invalid WeakMap key");k(f);if(!r(f,g))throw Error("WeakMap key fail: "+f);f[g][this.h]=h;return this};b.prototype.get=function(f){return d(f)&&r(f,g)?f[g][this.h]:void 0};b.prototype.has=function(f){return d(f)&&r(f,
g)&&r(f[g],this.h)};b.prototype.delete=function(f){return d(f)&&r(f,g)&&r(f[g],this.h)?delete f[g][this.h]:!1};return b});
y("Map",function(a){function b(){var e={};return e.previous=e.next=e.head=e}function c(e,f){var h=e[1];return J(function(){if(h){for(;h.head!=e[1];)h=h.previous;for(;h.next!=h.head;)return h=h.next,{done:!1,value:f(h)};h=null}return{done:!0,value:void 0}})}function d(e,f){var h=f&&typeof f;h=="object"||h=="function"?l.has(f)?h=l.get(f):(h=""+ ++g,l.set(f,h)):h="p_"+f;var m=e[0][h];if(m&&r(e[0],h))for(e=0;e<m.length;e++){var q=m[e];if(f!==f&&q.key!==q.key||f===q.key)return{id:h,list:m,index:e,entry:q}}return{id:h,
list:m,index:-1,entry:void 0}}function k(e){this[0]={};this[1]=b();this.size=0;if(e){e=p(e);for(var f;!(f=e.next()).done;)f=f.value,this.set(f[0],f[1])}}if(function(){if(!a||typeof a!="function"||!a.prototype.entries||typeof Object.seal!="function")return!1;try{var e=Object.seal({x:4}),f=new a(p([[e,"s"]]));if(f.get(e)!="s"||f.size!=1||f.get({x:4})||f.set({x:4},"t")!=f||f.size!=2)return!1;var h=f.entries(),m=h.next();if(m.done||m.value[0]!=e||m.value[1]!="s")return!1;m=h.next();return m.done||m.value[0].x!=
4||m.value[1]!="t"||!h.next().done?!1:!0}catch(q){return!1}}())return a;var l=new WeakMap;k.prototype.set=function(e,f){e=e===0?0:e;var h=d(this,e);h.list||(h.list=this[0][h.id]=[]);h.entry?h.entry.value=f:(h.entry={next:this[1],previous:this[1].previous,head:this[1],key:e,value:f},h.list.push(h.entry),this[1].previous.next=h.entry,this[1].previous=h.entry,this.size++);return this};k.prototype.delete=function(e){e=d(this,e);return e.entry&&e.list?(e.list.splice(e.index,1),e.list.length||delete this[0][e.id],
e.entry.previous.next=e.entry.next,e.entry.next.previous=e.entry.previous,e.entry.head=null,this.size--,!0):!1};k.prototype.clear=function(){this[0]={};this[1]=this[1].previous=b();this.size=0};k.prototype.has=function(e){return!!d(this,e).entry};k.prototype.get=function(e){return(e=d(this,e).entry)&&e.value};k.prototype.entries=function(){return c(this,function(e){return[e.key,e.value]})};k.prototype.keys=function(){return c(this,function(e){return e.key})};k.prototype.values=function(){return c(this,
function(e){return e.value})};k.prototype.forEach=function(e,f){for(var h=this.entries(),m;!(m=h.next()).done;)m=m.value,e.call(f,m[1],m[0],this)};k.prototype[Symbol.iterator]=k.prototype.entries;var g=0;return k});
y("Set",function(a){function b(c){this.h=new Map;if(c){c=p(c);for(var d;!(d=c.next()).done;)this.add(d.value)}this.size=this.h.size}if(function(){if(!a||typeof a!="function"||!a.prototype.entries||typeof Object.seal!="function")return!1;try{var c=Object.seal({x:4}),d=new a(p([c]));if(!d.has(c)||d.size!=1||d.add(c)!=d||d.size!=1||d.add({x:4})!=d||d.size!=2)return!1;var k=d.entries(),l=k.next();if(l.done||l.value[0]!=c||l.value[1]!=c)return!1;l=k.next();return l.done||l.value[0]==c||l.value[0].x!=4||
l.value[1]!=l.value[0]?!1:k.next().done}catch(g){return!1}}())return a;b.prototype.add=function(c){c=c===0?0:c;this.h.set(c,c);this.size=this.h.size;return this};b.prototype.delete=function(c){c=this.h.delete(c);this.size=this.h.size;return c};b.prototype.clear=function(){this.h.clear();this.size=0};b.prototype.has=function(c){return this.h.has(c)};b.prototype.entries=function(){return this.h.entries()};b.prototype.values=function(){return this.h.values()};b.prototype.keys=b.prototype.values;b.prototype[Symbol.iterator]=
b.prototype.values;b.prototype.forEach=function(c,d){var k=this;this.h.forEach(function(l){return c.call(d,l,l,k)})};return b});function ka(a){var b,c,d,k;return I(function(l){switch(l.h){case 1:return l.A(2),l.i(a.storage.session.get("beyondRoutingKey"),4);case 4:b=l.o;d=(c=b)==null?void 0:c.beyondRoutingKey;if(typeof d==="string"&&d.trim().length>0)return l.return(d.trim());l.D(3);break;case 2:k=l.v(),console.error("Failed to read beyondRoutingKey from storage:",k);case 3:return l.return(void 0)}})};var la="jan feb mar apr may jun jul aug sep oct nov dec".split(" ");function L(a){return a.length>1E3?a.slice(0,1E3)+"...":a}function M(a){return!(a==null||!a.message.includes("OFFSCREEN_MESSAGE_AUDIO_LEVEL_UPDATE"))}function N(a){this.capacity=a=a===void 0?1E3:a;this.size=this.h=0;this.buffer=Array(a)}function O(a,b){var c=(a.h-1+a.capacity)%a.capacity;a.size>0&&M(b)&&M(a.buffer[c])||(a.buffer[a.h]=b,a.h=(a.h+1)%a.capacity,a.size<a.capacity&&a.size++)}
function ma(a){for(var b=[],c=(a.h-a.size+a.capacity)%a.capacity,d=0;d<a.size;d++)b.push(a.buffer[c]),c=(c+1)%a.capacity;return b}N.prototype.clear=function(){this.size=this.h=0};var P=new N(1E3),Q="unknown";function S(a,b){b&&console.log("[VoiceTyping:"+a.module+"] "+a.timestamp+": "+a.message);Q==="test"?O(P,a):(Q!=="background"&&Q!=="unknown"||O(P,a),chrome.runtime.sendMessage({type:"MESSAGE_LOG_EVENT",entry:a}).catch(function(){}))}
function T(a,b){var c=ja.apply(2,arguments),d=Date.now(),k=b;c.length>0&&(c=c.map(function(l){if(l instanceof Error)return L(l.message);try{return typeof l==="object"&&l!==null?JSON.stringify(l,function(g,e){return typeof e==="string"?L(e):e}):L(String(l))}catch(g){return"[Serialization Error: "+(g instanceof Error?g.message:String(g))+"]"}}).join(" "),k+=" "+c);S({timestamp:d,module:a,message:k},!0)};function na(a){var b,c,d,k;return I(function(l){switch(l.h){case 1:return l.A(2),l.i(a.storage.session.get("oauthToken"),4);case 4:b=l.o;d=(c=b)==null?void 0:c.oauthToken;if(typeof d==="string"&&d.trim().length>0)return l.return(d.trim());l.D(3);break;case 2:k=l.v(),console.error("Failed to read oauthToken from storage:",k);case 3:return l.return(void 0)}})};function U(){this.h=chrome;this.j=new Set;this.l=new N;this.config={M:!1}}
U.prototype.o=function(a,b,c){a.type!=="MESSAGE_LOG_EVENT"&&T("Background","handleMessage",a);if(a.type==="OFFSCREEN_MESSAGE_READY"){T("Background","Offscreen document initialized");var d;(d=this.m)==null||d.call(this)}else if(a.type==="OFFSCREEN_MESSAGE_TRANSCRIPTION_UPDATE")this.h.dictationPrivate.updateTranscription({streamId:a.streamId,type:a.transcriptionType,data:a.text});else if(a.type==="OFFSCREEN_MESSAGE_STREAM_STATE_UPDATE")b={streamId:a.streamId,state:a.state},this.h.dictationPrivate.areAdditionalPropertiesIgnored&&
a.errorCode!==void 0&&(b.errorCode=a.errorCode),this.setStreamState(b);else if(a.type==="OFFSCREEN_MESSAGE_AUDIO_LEVEL_UPDATE"){var k,l;(l=(k=this.h.dictationPrivate).updateAudioLevel)==null||l.call(k,a.audioLevel).catch(function(g){T("Background","WARN: browser API error on audio level update: ",g)})}else a.type==="OFFSCREEN_MESSAGE_EVAL_DOWNLOAD"?oa(this,a.streamId,a.payload):a.type==="MESSAGE_LOG_EVENT"?O(this.l,a.entry):a.type==="DEBUG_MESSAGE_REQUEST_LOG_BUFFER"?c(ma(this.l)):T("Background",
"WARN: Unexpected message: ",a)};U.prototype.setStreamState=function(a){var b=this,c;return I(function(d){if(d.h==1)return d.A(2),d.i(b.h.dictationPrivate.setStreamState(a),4);if(d.h!=2)return d.D(0);c=d.v();T("Background","WARN: browser API error: ",c);d.I()})};
function oa(a,b,c){var d,k,l,g;I(function(e){if(e.h==1){T("Background","handleEvalDownload for stream "+b);d=(new TextEncoder).encode(c);k=d.toBase64();l="data:application/octet-stream;base64,"+k;e.A(2);var f=f===void 0?new Date:f;return e.i(a.h.downloads.download({url:l,filename:"voicetyping_eval_"+(la[f.getMonth()]+String(f.getDate()).padStart(2,"0")+"_"+String(f.getHours()).padStart(2,"0")+"_"+String(f.getMinutes()).padStart(2,"0")+"_"+String(f.getSeconds()).padStart(2,"0"))+".json",saveAs:!0}),
4)}if(e.h!=2)return e.D(0);g=e.v();T("Background","ERROR download failed "+b+":",g);e.I()})}
U.prototype.onStartStream=function(a,b,c){var d=this,k,l,g,e,f,h,m,q,t,w,z,A,W,X,R,Y,Z,aa;return I(function(u){switch(u.h){case 1:return T("Background","onStartStream: "+a),d.j.add(a),u.A(2,3),k=pa(d),l=d.h.systemPrivate.getApiKey(),g=na(d.h).then(function(ba){return ba?{token:ba}:d.config.M?d.h.identity.getAuthToken({interactive:!0}):null}),e=ka(d.h),f=p,u.i(Promise.all([l,g,e,k]),5);case 5:h=f(u.o);m=h.next().value;q=h.next().value;t=h.next().value;w=m;z=q;A=t;if(d.j.delete(a)){u.B(6);break}T("Background",
"Stream "+a+" ended before start completed; aborting.");return u.i(d.setStreamState({streamId:a,state:"complete"}),7);case 7:return u.return();case 6:T("Background","Using Routing Key: ",A);X=d.config.M||!((W=z)==null||!W.token);R=null;if(X){if((Y=z)==null||!Y.token)throw Error("Failed to authenticate user");R={scope:"https://www.googleapis.com/auth/googlenow",token:z.token}}Z=Object.assign({},{apiKey:w,oauth:R},A?{beyondRoutingKey:A}:{});return u.i(qa(d,{type:"BACKGROUND_MESSAGE_START_STREAM",streamId:a,
pageContext:b,config:Z,flags:c}),3);case 3:u.G();d.j.delete(a);u.K(0);break;case 2:return aa=u.v(),T("Background","Failed to start stream:",aa),u.i(d.setStreamState({streamId:a,state:"failed"}),3)}})};U.prototype.onEndStream=function(a){var b=this;return I(function(c){return c.h==1?(T("Background","onEndStream: "+a),b.j.delete(a)?(T("Background","Stream "+a+" ended while starting; will abort start."),c.return()):c.i(ra(b),2)):c.o?c.i(qa(b,{type:"BACKGROUND_MESSAGE_STOP_STREAM",streamId:a}),0):c.B(0)})};
function ra(a){var b,c;return I(function(d){if(d.h==1)return b=a.h.runtime.getURL("offscreen.html"),d.i(a.h.runtime.getContexts({contextTypes:["OFFSCREEN_DOCUMENT"],documentUrls:[b]}),2);c=d.o;return d.return(c.length>0)})}function qa(a,b){return a.h.runtime.sendMessage(b)}
function pa(a){return I(function(b){if(b.h==1)return a.i?b.i(a.i,3):b.B(2);if(b.h!=2)return b.return();a.i=function(){var c,d;return I(function(k){switch(k.h){case 1:return k.A(2,3),k.i(ra(a),5);case 5:if(k.o)return k.return();c=new Promise(function(l){a.m=l});return k.i(Promise.all([a.h.offscreen.createDocument({url:"offscreen.html",reasons:[a.h.offscreen.Reason.USER_MEDIA],justification:"Required for audio capture from microphone"}),c]),6);case 6:T("Background","Created OffscreenDocument");case 3:k.G();
a.i=void 0;a.m=void 0;k.K(0);break;case 2:throw d=k.v(),T("Background","ERROR: Failed to create offscreen document:",d),d;}})}();return b.i(a.i,0)})};var V=new U;P=V.l;Q="background";T("Background","Background initialized.");chrome.runtime.onMessage.addListener(V.o.bind(V));chrome.dictationPrivate.onStartStream.addListener(function(a){var b,c,d,k={annotatedPageContent:(b=a.context)==null?void 0:b.annotatedPageContent,pageContent:(c=a.context)==null?void 0:c.innerText,editableContent:(d=a.context)==null?void 0:d.editableContent};V.onStartStream(a.streamId,k,a.flags)});chrome.dictationPrivate.onContextUpdate.addListener(function(){});chrome.dictationPrivate.onEndStream.addListener(function(a){V.onEndStream(a.streamId)});
chrome.dictationPrivate.onBrowserLog&&chrome.dictationPrivate.onBrowserLog.addListener(function(a){a=p(a);var b=a.next(),c;try{for(;!b.done;b=a.next()){var d=b.value;S({timestamp:d.timestamp,module:"Browser",message:d.message},!1)}}finally{b&&!b.done&&(c=a.return)&&c.call(a)}});
