'use strict';var k=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};function r(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var t=r(this);
function u(a,b){if(b)a:{var c=t;a=a.split(".");for(var e=0;e<a.length-1;e++){var h=a[e];if(!(h in c))break a;c=c[h]}a=a[a.length-1];e=c[a];b=b(e);b!=e&&b!=null&&k(c,a,{configurable:!0,writable:!0,value:b})}}function w(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}
function x(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:w(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}function A(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");}function B(){this.A=!1;this.j=null;this.u=void 0;this.h=1;this.l=this.o=0;this.G=this.i=null}function C(a){if(a.A)throw new TypeError("Generator is already running");a.A=!0}
B.prototype.F=function(a){this.u=a};function D(a,b){a.i={K:b,isException:!0};a.h=a.o||a.l}B.prototype.getNextAddressJsc=function(){return this.h};B.prototype.getYieldResultJsc=function(){return this.u};B.prototype.return=function(a){this.i={return:a};this.h=this.l};B.prototype["return"]=B.prototype.return;B.prototype.M=function(a){this.i={H:a};this.l<a?(this.h=a,this.i=null):this.h=this.l};B.prototype.jumpThroughFinallyBlocks=B.prototype.M;B.prototype.m=function(a,b){this.h=b;return{value:a}};
B.prototype.yield=B.prototype.m;B.prototype.P=function(a,b){a=x(a);var c=a.next();A(c);if(c.done)this.u=c.value,this.h=b;else return this.j=a,this.m(c.value,b)};B.prototype.yieldAll=B.prototype.P;B.prototype.H=function(a){this.h=a};B.prototype.jumpTo=B.prototype.H;B.prototype.D=function(){this.h=0};B.prototype.jumpToEnd=B.prototype.D;B.prototype.C=function(a,b){this.o=a;b!=void 0&&(this.l=b)};B.prototype.setCatchFinallyBlocks=B.prototype.C;B.prototype.O=function(a){this.o=0;this.l=a||0};
B.prototype.setFinallyBlock=B.prototype.O;B.prototype.B=function(a,b){this.h=a;this.o=b||0};B.prototype.leaveTryBlock=B.prototype.B;B.prototype.v=function(a){this.o=a||0;a=this.i.K;this.i=null;return a};B.prototype.enterCatchBlock=B.prototype.v;B.prototype.J=function(a,b,c){c?this.G[c]=this.i:this.G=[this.i];this.o=a||0;this.l=b||0;this.i=null};B.prototype.enterFinallyBlock=B.prototype.J;
B.prototype.N=function(a,b){b=this.G.splice(b||0)[0];(b=this.i=this.i||b)?b.isException?this.h=this.o||this.l:b.H!=void 0&&this.l<b.H?(this.h=b.H,this.i=null):this.h=this.l:this.h=a};B.prototype.leaveFinallyBlock=B.prototype.N;B.prototype.L=function(a){return new E(a)};B.prototype.forIn=B.prototype.L;function E(a){this.j=a;this.h=[];for(var b in a)this.h.push(b);this.h.reverse()}E.prototype.i=function(){for(;this.h.length>0;){var a=this.h.pop();if(a in this.j)return a}return null};
E.prototype.getNext=E.prototype.i;function F(a){this.h=new B;this.i=a}function G(a,b){C(a.h);var c=a.h.j;if(c)return H(a,"return"in c?c["return"]:function(e){return{value:e,done:!0}},b,a.h.return);a.h.return(b);return I(a)}function H(a,b,c,e){try{var h=b.call(a.h.j,c);A(h);if(!h.done)return a.h.A=!1,h;var f=h.value}catch(d){return a.h.j=null,D(a.h,d),I(a)}a.h.j=null;e.call(a.h,f);return I(a)}
function I(a){for(;a.h.h;)try{var b=a.i(a.h);if(b)return a.h.A=!1,{value:b.value,done:!1}}catch(c){a.h.u=void 0,D(a.h,c)}a.h.A=!1;if(a.h.i){b=a.h.i;a.h.i=null;if(b.isException)throw b.K;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function J(a){this.next=function(b){C(a.h);a.h.j?b=H(a,a.h.j.next,b,a.h.F):(a.h.F(b),b=I(a));return b};this.throw=function(b){C(a.h);if(a.h.j){var c=a.h.j["throw"];if(c)var e=H(a,c,b,a.h.F);else{b=a.h.j;a.h.j=null;try{b["return"]&&(e=b["return"](),A(e)),D(a.h,new TypeError("The iterator does not provide a 'throw' method."))}catch(h){D(a.h,h)}e=I(a)}}else D(a.h,b),e=I(a);return e};this.return=function(b){return G(a,b)};this[Symbol.iterator]=function(){return this}}
function K(a){function b(e){return a.next(e)}function c(e){return a.throw(e)}return new Promise(function(e,h){function f(d){d.done?e(d.value):Promise.resolve(d.value).then(b,c).then(f,h)}f(a.next())})}function L(a){return K(new J(new F(a)))}
u("Symbol",function(a){function b(f){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(e+(f||"")+"_"+h++,f)}function c(f,d){this.h=f;k(this,"description",{configurable:!0,writable:!0,value:d})}if(a)return a;c.prototype.toString=function(){return this.h};var e="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",h=0;return b});
u("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");k(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return M(w(this))}});return a});function M(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
u("Promise",function(a){function b(d){this.i=0;this.j=void 0;this.h=[];this.u=!1;var g=this.l();try{d(g.resolve,g.reject)}catch(l){g.reject(l)}}function c(){this.h=null}function e(d){return d instanceof b?d:new b(function(g){g(d)})}if(a)return a;c.prototype.i=function(d){if(this.h==null){this.h=[];var g=this;this.j(function(){g.m()})}this.h.push(d)};var h=t.setTimeout;c.prototype.j=function(d){h(d,0)};c.prototype.m=function(){for(;this.h&&this.h.length;){var d=this.h;this.h=[];for(var g=0;g<d.length;++g){var l=
d[g];d[g]=null;try{l()}catch(m){this.l(m)}}}this.h=null};c.prototype.l=function(d){this.j(function(){throw d;})};b.prototype.l=function(){function d(m){return function(n){l||(l=!0,m.call(g,n))}}var g=this,l=!1;return{resolve:d(this.D),reject:d(this.m)}};b.prototype.D=function(d){if(d===this)this.m(new TypeError("A Promise cannot resolve to itself"));else if(d instanceof b)this.G(d);else{a:switch(typeof d){case "object":var g=d!=null;break a;case "function":g=!0;break a;default:g=!1}g?this.C(d):this.o(d)}};
b.prototype.C=function(d){var g=void 0;try{g=d.then}catch(l){this.m(l);return}typeof g=="function"?this.J(g,d):this.o(d)};b.prototype.m=function(d){this.v(2,d)};b.prototype.o=function(d){this.v(1,d)};b.prototype.v=function(d,g){if(this.i!=0)throw Error("Cannot settle("+d+", "+g+"): Promise already settled in state"+this.i);this.i=d;this.j=g;this.i===2&&this.F();this.A()};b.prototype.F=function(){var d=this;h(function(){if(d.B()){var g=t.console;typeof g!=="undefined"&&g.error(d.j)}},1)};b.prototype.B=
function(){if(this.u)return!1;var d=t.CustomEvent,g=t.Event,l=t.dispatchEvent;if(typeof l==="undefined")return!0;typeof d==="function"?d=new d("unhandledrejection",{cancelable:!0}):typeof g==="function"?d=new g("unhandledrejection",{cancelable:!0}):(d=t.document.createEvent("CustomEvent"),d.initCustomEvent("unhandledrejection",!1,!0,d));d.promise=this;d.reason=this.j;return l(d)};b.prototype.A=function(){if(this.h!=null){for(var d=0;d<this.h.length;++d)f.i(this.h[d]);this.h=null}};var f=new c;b.prototype.G=
function(d){var g=this.l();d.I(g.resolve,g.reject)};b.prototype.J=function(d,g){var l=this.l();try{d.call(g,l.resolve,l.reject)}catch(m){l.reject(m)}};b.prototype.then=function(d,g){function l(p,q){return typeof p=="function"?function(y){try{m(p(y))}catch(v){n(v)}}:q}var m,n,z=new b(function(p,q){m=p;n=q});this.I(l(d,m),l(g,n));return z};b.prototype.catch=function(d){return this.then(void 0,d)};b.prototype.I=function(d,g){function l(){switch(m.i){case 1:d(m.j);break;case 2:g(m.j);break;default:throw Error("Unexpected state: "+
m.i);}}var m=this;this.h==null?f.i(l):this.h.push(l);this.u=!0};b.resolve=e;b.reject=function(d){return new b(function(g,l){l(d)})};b.race=function(d){return new b(function(g,l){for(var m=x(d),n=m.next();!n.done;n=m.next())e(n.value).I(g,l)})};b.all=function(d){var g=x(d),l=g.next();return l.done?e([]):new b(function(m,n){function z(y){return function(v){p[y]=v;q--;q==0&&m(p)}}var p=[],q=0;do p.push(void 0),q++,e(l.value).I(z(p.length-1),n),l=g.next();while(!l.done)})};return b});
u("Object.is",function(a){return a?a:function(b,c){return b===c?b!==0||1/b===1/c:b!==b&&c!==c}});u("Array.prototype.includes",function(a){return a?a:function(b,c){var e=this;e instanceof String&&(e=String(e));var h=e.length;c=c||0;for(c<0&&(c=Math.max(c+h,0));c<h;c++){var f=e[c];if(f===b||Object.is(f,b))return!0}return!1}});
function N(a,b,c){if(a==null)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""}u("String.prototype.includes",function(a){return a?a:function(b,c){return N(this,b,"includes").indexOf(b,c||0)!==-1}});
u("String.prototype.repeat",function(a){return a?a:function(b){var c=N(this,null,"repeat");if(b<0||b>1342177279)throw new RangeError("Invalid count value");b|=0;for(var e="";b;)if(b&1&&(e+=c),b>>>=1)c+=c;return e}});u("String.prototype.padStart",function(a){return a?a:function(b,c){var e=N(this,null,"padStart");b-=e.length;c=c!==void 0?String(c):" ";return(b>0&&c?c.repeat(Math.ceil(b/c.length)).substring(0,b):"")+e}});
u("Array.prototype.find",function(a){return a?a:function(b,c){a:{var e=this;e instanceof String&&(e=String(e));for(var h=e.length,f=0;f<h;f++){var d=e[f];if(b.call(c,d,f,e)){b=d;break a}}b=void 0}return b}});function aa(){var a=chrome,b,c,e,h;return L(function(f){switch(f.h){case 1:return f.C(2),f.m(a.storage.session.get("beyondRoutingKey"),4);case 4:b=f.u;e=(c=b)==null?void 0:c.beyondRoutingKey;if(typeof e==="string"&&e.trim().length>0)return f.return(e.trim());f.B(3);break;case 2:h=f.v(),console.error("Failed to read beyondRoutingKey from storage:",h);case 3:return f.return(void 0)}})}
function ba(){var a=chrome,b=O.value,c,e,h,f;L(function(d){if(d.h==1)return e=(c=b)==null?void 0:c.trim(),d.C(2),e?(h={},d.m(a.storage.session.set((h.beyondRoutingKey=e,h)),5)):d.m(a.storage.session.remove("beyondRoutingKey"),5);if(d.h!=2)return d.B(0);f=d.v();console.error("Failed to write beyondRoutingKey to storage:",f);d.D()})};function P(a){return!(a==null||!a.message.includes("OFFSCREEN_MESSAGE_AUDIO_LEVEL_UPDATE"))};function ca(){var a=chrome,b,c,e,h;return L(function(f){switch(f.h){case 1:return f.C(2),f.m(a.storage.session.get("oauthToken"),4);case 4:b=f.u;e=(c=b)==null?void 0:c.oauthToken;if(typeof e==="string"&&e.trim().length>0)return f.return(e.trim());f.B(3);break;case 2:h=f.v(),console.error("Failed to read oauthToken from storage:",h);case 3:return f.return(void 0)}})}
function da(){var a=chrome,b=Q.value,c,e,h,f;L(function(d){if(d.h==1)return e=(c=b)==null?void 0:c.trim(),d.C(2),e?(h={},d.m(a.storage.session.set((h.oauthToken=e,h)),5)):d.m(a.storage.session.remove("oauthToken"),5);if(d.h!=2)return d.B(0);f=d.v();console.error("Failed to write oauthToken to storage:",f);d.D()})};/*

 Copyright Google LLC
 SPDX-License-Identifier: Apache-2.0
*/
function R(a){this.h=a}R.prototype.toString=function(){return this.h};var ea=/^\s*(?!javascript:)(?:[\w+.-]+:|[^:/?#]*(?:[/?#]|$))/i;var S=document.getElementById("log-container"),T=document.getElementById("filter-background"),U=document.getElementById("filter-offscreen"),V=document.getElementById("filter-browser"),fa=document.getElementById("export-btn"),O=document.getElementById("routing-key-input");O&&(aa().then(function(a){a&&(O.value=a)}),O.addEventListener("input",function(){ba()}));var Q=document.getElementById("oauth-token-input");Q&&(ca().then(function(a){a&&(Q.value=a)}),Q.addEventListener("input",function(){da()}));
var W=[];
function X(a){var b=W.length;if(b===0||a.timestamp>=W[b-1].timestamp)var c=b;else for(c=0,--b;c<=b;){var e=Math.floor((c+b)/2);W[e].timestamp<=a.timestamp?c=e+1:b=e-1}if(!P(a)||!P(W[c-1])&&!P(W[c])){b=S.scrollHeight-S.clientHeight-S.scrollTop<2;W.splice(c,0,a);e=document.createElement("div");e.className="log-entry";e.dataset.module=a.module.toLowerCase();var h=document.createElement("span");h.className="log-timestamp";var f=new Date(a.timestamp);h.textContent=f.getFullYear()+"-"+String(f.getMonth()+1).padStart(2,
"0")+"-"+String(f.getDate()).padStart(2,"0")+" "+String(f.getHours()).padStart(2,"0")+":"+String(f.getMinutes()).padStart(2,"0");f=document.createElement("span");f.className="log-module module-"+a.module.toLowerCase();f.textContent="["+a.module+"]";var d=document.createElement("span");d.textContent=" "+a.message;e.appendChild(h);e.appendChild(f);e.appendChild(d);e.classList.toggle("hidden",!Y(a.module));c<S.children.length?S.insertBefore(e,S.children[c]):S.appendChild(e);b&&(S.scrollTop=S.scrollHeight)}}
function Y(a){switch(a.toLowerCase()){case "background":return T.checked;case "offscreen":return U.checked;case "browser":return V.checked;default:return!0}}function Z(){var a=x(S.querySelectorAll(".log-entry")),b=a.next(),c;try{for(;!b.done;b=a.next()){var e=b.value,h=e.dataset.module;h&&e.classList.toggle("hidden",!Y(h))}}finally{b&&!b.done&&(c=a.return)&&c.call(a)}}T.addEventListener("change",Z);U.addEventListener("change",Z);V.addEventListener("change",Z);
fa.addEventListener("click",function(){var a=new Blob([JSON.stringify(W,null,2)],{type:"application/octet-stream"});var b=window;(b=typeof MediaSource!=="undefined"&&a instanceof MediaSource||typeof b.ManagedMediaSource!=="undefined"&&a instanceof b.ManagedMediaSource)||(b=a.type,b.toLowerCase()==="application/octet-stream"?b=!0:(b=b.match(/^([^;]+)(?:;\w+=(?:\w+|"[\w;,= ]+"))*$/i),b=(b==null?void 0:b.length)===2&&(/^image\/(?:bmp|gif|jpeg|jpg|png|tiff|webp|x-icon|heic|heif|avif|x-ms-bmp)$/i.test(b[1])||
/^video\/(?:3gpp|avi|mpeg|mpg|mp4|ogg|webm|x-flv|matroska|x-matroska|quicktime|x-ms-wmv)$/i.test(b[1])||/^audio\/(?:3gpp2|3gpp|aac|amr|L16|midi|mp3|mp4|mpeg|oga|ogg|opus|x-m4a|matroska|x-matroska|x-wav|wav|webm)$/i.test(b[1])||/^font\/[\w-]+$/i.test(b[1]))));if(!b)throw Error("");a=URL.createObjectURL(a);a=new R(a);b=document.createElement("a");if(a instanceof R)if(a instanceof R)var c=a.h;else throw Error("");else c=ea.test(a)?a:void 0;c!==void 0&&(b.href=c);b.download="voicetyping_debug_logs_"+
(new Date).toISOString()+".json";b.click();URL.revokeObjectURL(a.toString())});chrome.runtime.onMessage.addListener(function(a){a.type==="MESSAGE_LOG_EVENT"&&X(a.entry)});
chrome.runtime.sendMessage({type:"DEBUG_MESSAGE_REQUEST_LOG_BUFFER"},function(a){var b,c,e,h,f,d,g,l,m,n,z,p,q,y;return L(function(v){if(v.h==1){b=Date.now();if(a&&a.length>0){c=x(a);e=c.next();try{for(;!e.done;e=c.next())f=e.value,f.timestamp<b&&(b=f.timestamp)}finally{e&&!e.done&&(h=c.return)&&h.call(c)}}W.length>0&&W[0].timestamp<b&&(b=W[0].timestamp);d=b-1;return v.m(navigator.userAgentData.getHighEntropyValues(["fullVersionList"]),2)}g=v.u;n=(l=g.fullVersionList)==null?void 0:(m=l.find(function(ha){return ha.brand===
"Chromium"}))==null?void 0:m.version;n||(n=(z=navigator.userAgent.match(/Chrome\/([0-9.]+)/))?z[1]:navigator.userAgent);p=chrome.runtime.getManifest();q=p.version_name||p.version;y=[{timestamp:d,module:"System",message:"Extension Version: "+q},{timestamp:d,module:"System",message:"Chrome Version: "+n}];y.forEach(X);a&&a.forEach(X);v.D()})});
